### PR TITLE
fix: maven config to the right directory

### PR DESCRIPTION
**Pull request by nicufk**
## Pull request description 

Closes: https://github.com/kubeshop/testkube/issues/3001

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

### CODE REVIEW

**Review by vLia — APPROVED** [review]
Looks good, but will this work with https://github.com/kubeshop/testkube-executor-maven/blob/main/pkg/runner/runner.go#L97 ?

**Comment by nicufk** [comment]
> Looks good, but will this work with https://github.com/kubeshop/testkube-executor-maven/blob/main/pkg/runner/runner.go#L97 ?

This is a good point, Thanks. It is working on the testing I've made.

**Review by vsukhin — APPROVED** [review]

**Comment by nicufk** [comment]
> Looks good, but will this work with https://github.com/kubeshop/testkube-executor-maven/blob/main/pkg/runner/runner.go#L97 ?

it seems that the maven dependency manager runs in a different environment context and is not affected by this change

**Comment by vLia** [comment]
> > Looks good, but will this work with https://github.com/kubeshop/testkube-executor-maven/blob/main/pkg/runner/runner.go#L97 ?
> 
> it seems that the maven dependency manager runs in a different environment context and is not affected by this change

That is very good news! Glad it works now \o/

**Pull request merged**
